version: '3.8'

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost-blog
    ports:
      - "2368:2368"
    environment:
      NODE_ENV: production
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      database__useNullAsDefault: "true"
    restart: unless-stopped
