version: '3.8'

services:
  ghost-be:
    image: ghost:5-alpine
    container_name: ghost-backend
    ports:
      - "2368:2368"
    environment:
      NODE_ENV: production
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      database__useNullAsDefault: "true"
      # Enable private site mode to disable public frontend
      privacy__useUpdateCheck: "false"
      privacy__useGravatar: "false"
      privacy__useRpcPing: "false"
      privacy__useStripe: "false"
    restart: unless-stopped
